spring:
  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:testdb
     username: sa
     password: "{cipher}AQB3Kn7CUOPeGYqBwwlk+cluDbXShSFtTqv6H75Pl3WmStlxpWB//gHTSFWHsLEGFgPpGIquGVoKFo5EtfLjj4D3nLYfblq7FVttARoxL6SDt9RMJkAOQsBg4kb32ONwvzSL1JLV3S2Xb8h3/QvFzEaZCPrqAhZ8DDxYC1fH5nSsPAn5E7Tzkz/HQ/eOK8GBP9+pkBcLoF0mFuPa/xWJqSkpWwhYvO+iMDmE+8AXiuIJ0FAlJsvP12ejsxnoLElbK8jjqWgdh2F7qYzjh4rriDnR+GJcvfbC6CgZhTDRvnM5/JVuUiaDQ59qUFCEkfZz1eK+0Qloa3GR7d9B92FZr8QNofm9odTQ3JXWzmFCBzfHsq/SzllJSuhG3fC98tKZjQw="
     # #{cipher} 뒤에가 암호값이라는걸 의미
  #임의 값
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  
token:
  expiration_time: 86400000
  secret: "{cipher}AQBqcsRDh8NWeU2zcyCNT1A23uri13vX/7nXNYDKt4awLmUVXzmrNLur+a4jgZ6hhrssqE3JkJi9gMtLy0hLUY177Hoh2C/ZMnOAYpz6x9g5GvGMGQCdBblqZVTGER3Tye7fC8X3S4T0uKeOONVDP79pgybgYCFMegxBKzEPUY1ju/Z9s5LNm3N+8rwfZK89NJx/zkUVIgOe1Gv163JcgUz0k4GkD5a1AwrR5E2bHeFZ6Br59gYG0BOE0nP8dWf2TGXJ3/ikbhhPX7+C4A4Dxy8YUHPbNMsYf643/Uer5ZQhP2VNRcPGjz61SAWJ+8XIL7Ejqjmn7t00DbV943KX0Dgd54ngJ4RmNkjyhz/101FLl+XFjZYIdE8BZsq1tbN1BNg="
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty
